<<<<<<< HEAD
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "transformations"
version: "1.0"

# This setting configures which "profile" dbt uses for this project. Profiles contain
# database connection information, and should be configured in the  ~/.dbt/profiles.yml file
profile: "snowflake"

# Ensure correct quoting for snowflake
quoting:
  database: false
  identifier: false
  schema: false

# Snapshot config setting for transient vs non-transient tables in snowflake
snapshots:
  transient: false

# Specify a minimum boundary on a dbt version
# Any version greater than or equal to 0.13.0 is supported
require-dbt-version: ">=0.16.0"

# These configurations specify where dbt should look for different types of files.
=======

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
>>>>>>> 538f38a152eb748979c77b2410b7a8ec407b94fc
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

<<<<<<< HEAD
target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
=======
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
>>>>>>> 538f38a152eb748979c77b2410b7a8ec407b94fc

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
      # Applies to all files under models/example/
      example:
          materialized: view
